/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.CarController;
import model.Car;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tejas Shahi
 */
public class AddToCart extends javax.swing.JDialog {

    private CarController controller;
    private ArrayList<Car> cartList;
    private boolean itemAdded = false;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddToCart.class.getName());

    /**
     * Creates new form AddToCart
     */
    // Updated to accept Controller and CartList
    public AddToCart(java.awt.Frame parent, boolean modal, CarController controller, ArrayList<Car> cartList) {
        super(parent, modal);
        initComponents();
        this.controller = controller;
        this.cartList = cartList;
        populateCarCombo(); // Call the helper method to fill the list
    }

    private void populateCarCombo() {
        if (controller == null) {
            return;
        }

        ArrayList<Car> inventory = controller.getAllCars();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        for (Car car : inventory) {
            // Only show cars that have stock available
            if (car.getStockQuantity() > 0) {
                // Format: "ID - Model (Price)"
                model.addElement(car.getCarId() + " - " + car.getModel() + " ($" + car.getPrice() + ")");
            }
        }
        jComboBox1.setModel(model);
    }

    // Getter to let Dashboard know if we clicked "Add"
    public boolean isItemAdded() {
        return itemAdded;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 5));
        jPanel8.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("ADD DETAILS");
        jPanel8.add(jLabel3);
        jLabel3.setBounds(310, 10, 150, 32);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Select Car Model :");
        jPanel8.add(jLabel5);
        jLabel5.setBounds(240, 80, 200, 20);

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("START ENGINE");
        jPanel8.add(jButton1);
        jButton1.setBounds(230, 310, 140, 40);

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel8.add(jButton2);
        jButton2.setBounds(410, 150, 150, 50);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(jComboBox1);
        jComboBox1.setBounds(420, 80, 140, 22);

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Add To Cart");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel8.add(jButton3);
        jButton3.setBounds(220, 150, 150, 50);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(70, 50, 760, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // 1. Get Selected Car String
            String selectedStr = (String) jComboBox1.getSelectedItem();
            if (selectedStr == null) {
                JOptionPane.showMessageDialog(this, "No car selected!");
                return;
            }

            // 2. Extract ID (It's the number before " - ")
            int id = Integer.parseInt(selectedStr.split(" - ")[0]);


            // 4. Validate
            Car selectedCar = controller.getCarById(id);


            // 5. Add to Cart
            // Note: Since this is a draft cart, we are just adding the reference for now
            // In a full system, you might create a "CartItem" object with specific qty
            cartList.add(selectedCar);

            itemAdded = true;
            this.dispose(); // Close dialog

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for quantity.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}