/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Dell
 */
public class DashboardFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());
    private java.util.ArrayList<model.Car> currentCart = new java.util.ArrayList<>();

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
        loadTableData();
    }
    // 1. Updates the "Shopping Cart" table on the left

    public void refreshCartTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblCart.getModel();
        model.setRowCount(0); // Clear rows

        for (model.Car car : currentCart) {
            model.addRow(new Object[]{car.getCarId(), car.getBrand(), car.getModel(), car.getPrice()});
        }
    }

// 2. Updates the "Pending Orders" table (Reads from Manual Queue)
    public void refreshPendingTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPending.getModel();
        model.setRowCount(0);

        // This uses the getItems() helper we added in Step 1
        model.Sale[] queueItems = controller.getPendingQueue().getItems();

        for (model.Sale sale : queueItems) {
            if (sale != null) {
                model.addRow(new Object[]{"Pending", sale.getCustomerName(), sale.getTotalAmount()});
            }
        }
    }

// 3. Updates the "Sales History" table (Reads from Manual Stack)
    public void refreshHistoryTable() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblHistory.getModel();
        model.setRowCount(0);

        // This uses the getItems() helper we added in Step 1
        model.Sale[] stackItems = controller.getSalesHistory().getItems();

        for (int i = stackItems.length - 1; i >= 0; i--) {
            model.Sale sale = stackItems[i];
            if (sale != null) {
                model.addRow(new Object[]{"Confirmed", sale.getCustomerName(), sale.getTotalAmount()});
            }
        }
    }
    controller.CarController controller = new controller.CarController();

    public void loadTableData() {
        controller.CarController controller = new controller.CarController();

        // CHANGED: LinkedList -> ArrayList
        java.util.ArrayList<model.Car> cars = controller.getAllCars();

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) readTable.getModel();
        model.setRowCount(0); // Clear table

        for (model.Car car : cars) {
            Object[] row = {
                car.getCarId(),
                car.getBrand(),
                car.getModel(),
                car.getYear(),
                car.getPrice(),
                car.getStockQuantity()
            };
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        readTable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        cmbSort = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtId1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtModel1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPrice1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtQuantity1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDeleteId = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtCustomerPhone = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPending = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("BMW - SHOWROOM MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 10, 840, 100);

        jTabbedPane1.setToolTipText("");

        jPanel3.setLayout(null);

        readTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CarID", "Brand", "Model", "Year", "Price", "Stock Qty"
            }
        ));
        jScrollPane1.setViewportView(readTable);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 56, 800, 290);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(530, 10, 220, 22);

        jButton3.setText("Sort");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(170, 10, 72, 23);

        cmbSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Price(Low To High)", "Price(High To Low)" }));
        jPanel3.add(cmbSort);
        cmbSort.setBounds(20, 10, 135, 22);

        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(760, 10, 72, 23);

        jTabbedPane1.addTab("Main Dashboard", jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel7.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 5));
        jPanel8.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("ADD DETAILS");
        jPanel8.add(jLabel3);
        jLabel3.setBounds(310, 10, 150, 32);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("ID :");
        jPanel8.add(jLabel5);
        jLabel5.setBounds(40, 80, 120, 20);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel8.add(txtId);
        txtId.setBounds(160, 80, 200, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Model :");
        jPanel8.add(jLabel6);
        jLabel6.setBounds(40, 120, 120, 20);

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });
        jPanel8.add(txtModel);
        txtModel.setBounds(160, 120, 200, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Price :");
        jPanel8.add(jLabel7);
        jLabel7.setBounds(40, 160, 120, 20);

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        jPanel8.add(txtPrice);
        txtPrice.setBounds(160, 160, 200, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Quantity :");
        jPanel8.add(jLabel8);
        jLabel8.setBounds(390, 160, 120, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Brand :");
        jPanel8.add(jLabel9);
        jLabel9.setBounds(390, 80, 120, 20);

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });
        jPanel8.add(txtBrand);
        txtBrand.setBounds(510, 80, 200, 22);

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });
        jPanel8.add(txtYear);
        txtYear.setBounds(510, 120, 200, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("Year :");
        jPanel8.add(jLabel10);
        jLabel10.setBounds(390, 120, 120, 20);

        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        jPanel8.add(txtQuantity);
        txtQuantity.setBounds(510, 160, 200, 22);

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("START ENGINE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1);
        jButton1.setBounds(230, 310, 140, 40);

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add Model");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2);
        jButton2.setBounds(300, 210, 150, 50);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(40, 40, 760, 280);

        jPanel4.add(jPanel7);

        jTabbedPane1.addTab("Create Model", jPanel4);

        jPanel5.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 5));
        jPanel9.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("UPDATE ");
        jPanel9.add(jLabel4);
        jLabel4.setBounds(340, 10, 100, 32);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setText("ID :");
        jPanel9.add(jLabel11);
        jLabel11.setBounds(40, 80, 120, 20);

        txtId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId1ActionPerformed(evt);
            }
        });
        jPanel9.add(txtId1);
        txtId1.setBounds(160, 80, 200, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setText("Model :");
        jPanel9.add(jLabel12);
        jLabel12.setBounds(40, 130, 120, 20);

        txtModel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModel1ActionPerformed(evt);
            }
        });
        jPanel9.add(txtModel1);
        txtModel1.setBounds(160, 130, 200, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel13.setText("Price :");
        jPanel9.add(jLabel13);
        jLabel13.setBounds(390, 80, 120, 20);

        txtPrice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrice1ActionPerformed(evt);
            }
        });
        jPanel9.add(txtPrice1);
        txtPrice1.setBounds(510, 80, 200, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel14.setText("Quantity :");
        jPanel9.add(jLabel14);
        jLabel14.setBounds(390, 130, 120, 20);

        txtQuantity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantity1ActionPerformed(evt);
            }
        });
        jPanel9.add(txtQuantity1);
        txtQuantity1.setBounds(510, 130, 200, 22);

        jButton4.setBackground(new java.awt.Color(0, 0, 102));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("START ENGINE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton4);
        jButton4.setBounds(230, 310, 140, 40);

        jButton5.setBackground(new java.awt.Color(0, 0, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Update Model");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton5);
        jButton5.setBounds(300, 190, 150, 50);

        jPanel5.add(jPanel9);
        jPanel9.setBounds(40, 40, 760, 280);

        jTabbedPane1.addTab("Update Model", jPanel5);

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 5));
        jPanel10.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("DELETE ");
        jPanel10.add(jLabel15);
        jLabel15.setBounds(340, 10, 100, 32);

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel16.setText("ID :");
        jPanel10.add(jLabel16);
        jLabel16.setBounds(220, 80, 120, 50);

        txtDeleteId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteIdActionPerformed(evt);
            }
        });
        jPanel10.add(txtDeleteId);
        txtDeleteId.setBounds(300, 80, 270, 60);

        jButton6.setBackground(new java.awt.Color(0, 0, 102));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("START ENGINE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton6);
        jButton6.setBounds(230, 310, 140, 40);

        jButton7.setBackground(new java.awt.Color(0, 0, 102));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("DELETE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton7);
        jButton7.setBounds(300, 180, 150, 50);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Delete Model", jPanel6);

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 5));
        jPanel13.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("CART");
        jPanel13.add(jLabel17);
        jLabel17.setBounds(30, 110, 280, 32);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel18.setText("Name:");
        jPanel13.add(jLabel18);
        jLabel18.setBounds(40, 60, 120, 20);

        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        jPanel13.add(txtCustomerName);
        txtCustomerName.setBounds(160, 60, 200, 22);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel22.setText("Phone :");
        jPanel13.add(jLabel22);
        jLabel22.setBounds(440, 60, 120, 20);

        txtCustomerPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerPhoneActionPerformed(evt);
            }
        });
        jPanel13.add(txtCustomerPhone);
        txtCustomerPhone.setBounds(560, 60, 200, 22);

        jButton9.setBackground(new java.awt.Color(0, 0, 102));
        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Make Sale");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton9);
        jButton9.setBounds(650, 300, 120, 30);

        jButton10.setBackground(new java.awt.Color(0, 0, 102));
        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Add Item");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton10);
        jButton10.setBounds(640, 100, 120, 30);

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CarID", "Brand", "Model", "Price"
            }
        ));
        jScrollPane2.setViewportView(tblCart);

        jPanel13.add(jScrollPane2);
        jScrollPane2.setBounds(20, 150, 790, 140);

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setText("ADD CUSTOMER DETAIL");
        jPanel13.add(jLabel19);
        jLabel19.setBounds(290, 10, 280, 32);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Make Sale", jPanel12);

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 5));
        jPanel15.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("CART");
        jPanel15.add(jLabel20);
        jLabel20.setBounds(30, 50, 280, 32);

        jButton11.setBackground(new java.awt.Color(0, 0, 102));
        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Confirm Sale");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton11);
        jButton11.setBounds(680, 300, 120, 30);

        tblPending.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Queue #", "Customer Name", "Total Amount"
            }
        ));
        jScrollPane3.setViewportView(tblPending);

        jPanel15.add(jScrollPane3);
        jScrollPane3.setBounds(20, 90, 790, 200);

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 102));
        jLabel24.setText("Confim Sale");
        jPanel15.add(jLabel24);
        jLabel24.setBounds(350, 10, 140, 32);

        jButton13.setBackground(new java.awt.Color(0, 0, 102));
        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Cancle Sale");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton13);
        jButton13.setBounds(550, 300, 120, 30);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Confirm Sale", jPanel14);

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 5));
        jPanel17.setLayout(null);

        jButton12.setBackground(new java.awt.Color(0, 0, 102));
        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Undo Last Sale");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton12);
        jButton12.setBounds(630, 50, 160, 30);

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "SaleID", "Customer Name", "Total Paid"
            }
        ));
        jScrollPane4.setViewportView(tblHistory);

        jPanel17.add(jScrollPane4);
        jScrollPane4.setBounds(20, 90, 790, 240);

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setText("Sale History");
        jPanel17.add(jLabel25);
        jLabel25.setBounds(360, 10, 140, 32);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Sale History", jPanel16);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(30, 130, 840, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // 1. Validate: Check for empty fields
        if (txtId.getText().trim().isEmpty() || txtBrand.getText().trim().isEmpty()
                || txtModel.getText().trim().isEmpty() || txtYear.getText().trim().isEmpty()
                || txtPrice.getText().trim().isEmpty() || txtQuantity.getText().trim().isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this, "All fields are required.", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. Validate: Parse numbers
            int id = Integer.parseInt(txtId.getText().trim());
            String brand = txtBrand.getText().trim();
            String model = txtModel.getText().trim();
            int year = Integer.parseInt(txtYear.getText().trim());
            double price = Double.parseDouble(txtPrice.getText().trim());
            int quantity = Integer.parseInt(txtQuantity.getText().trim());

            // 3. Validate: Check for positive values
            if (id < 0 || price < 0 || quantity < 0 || year < 1886) {
                javax.swing.JOptionPane.showMessageDialog(this, "ID, Price, Quantity, and Year must be valid positive numbers.", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 4. Create Object and Call Controller
            controller.CarController carController = new controller.CarController();
            model.Car newCar = new model.Car(id, brand, model, year, price, quantity);

            // Capture the boolean result (True = Added, False = Duplicate ID)
            boolean isAdded = carController.registerCar(newCar);

            if (isAdded) {
                // SUCCESS
                javax.swing.JOptionPane.showMessageDialog(this, "Car Added Successfully.");

                // Clear fields
                txtId.setText("");
                txtBrand.setText("");
                txtModel.setText("");
                txtYear.setText("");
                txtPrice.setText("");
                txtQuantity.setText("");

                // Refresh the table immediately
                loadTableData();

            } else {
                // FAILURE (Duplicate ID)
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Car ID " + id + " already exists! Please use a unique ID.",
                        "Duplicate Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            // Catches any non-numeric input for ID, Year, Price, Quantity
            javax.swing.JOptionPane.showMessageDialog(this, "ID, Year, Price, and Quantity must be numeric values.", "Format Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        loadTableData();
        refreshCartTable();
        refreshPendingTable();
        refreshHistoryTable();
    }//GEN-LAST:event_formWindowActivated

    private void txtId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId1ActionPerformed

    private void txtModel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModel1ActionPerformed

    private void txtPrice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrice1ActionPerformed

    private void txtQuantity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantity1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        // 1. ID is required to find the car
        if (txtId1.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter the Car ID to update.", "Missing ID", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = Integer.parseInt(txtId1.getText().trim());

            // 2. Fetch the existing car data
            // (Make sure you initialized 'controller' at the top of your class)
            model.Car existingCar = controller.getCarById(id);

            if (existingCar == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Car ID not found.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. Determine New Values (Logic: If field is empty, keep old value)
            // Model
            String newModel;
            if (txtModel1.getText().trim().isEmpty()) {
                newModel = existingCar.getModel(); // Keep old
            } else {
                newModel = txtModel1.getText().trim(); // Use new
            }

            // Price
            double newPrice;
            if (txtPrice1.getText().trim().isEmpty()) {
                newPrice = existingCar.getPrice(); // Keep old
            } else {
                newPrice = Double.parseDouble(txtPrice1.getText().trim()); // Use new
            }

            // Quantity
            int newQuantity;
            if (txtQuantity1.getText().trim().isEmpty()) {
                newQuantity = existingCar.getStockQuantity(); // Keep old
            } else {
                newQuantity = Integer.parseInt(txtQuantity1.getText().trim()); // Use new
            }

            // 4. CHECK: Did anything actually change?
            if (newModel.equals(existingCar.getModel())
                    && newPrice == existingCar.getPrice()
                    && newQuantity == existingCar.getStockQuantity()) {

                javax.swing.JOptionPane.showMessageDialog(this, "No changes were made.", "Update Info", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                return; // Stop here
            }

            // 5. Validate Negatives
            if (newPrice < 0 || newQuantity < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Price and Quantity cannot be negative.", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 6. Perform the Update
            controller.updateCar(id, newModel, newPrice, newQuantity);

            javax.swing.JOptionPane.showMessageDialog(this, "Car details updated successfully!");

            // Refresh and Clear
            loadTableData();
            txtId1.setText("");
            txtModel1.setText("");
            txtPrice1.setText("");
            txtQuantity1.setText("");

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID, Price, and Quantity must be valid numbers.", "Format Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtDeleteIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeleteIdActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        // 1. Validation
        if (txtDeleteId.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter the Car ID to delete.", "Missing ID", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. Parse ID
            int id = Integer.parseInt(txtDeleteId.getText().trim());

            // 3. Call Controller directly (No Confirmation)
            controller.CarController carController = new controller.CarController();
            boolean deleted = carController.deleteCar(id);

            if (deleted) {
                javax.swing.JOptionPane.showMessageDialog(this, "Car Record Deleted Successfully.");
                loadTableData(); // Refresh Table
                txtDeleteId.setText(""); // Clear field
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Car ID not found.", "Delete Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Car ID must be a valid number.", "Format Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void txtCustomerPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerPhoneActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        // 1. Validation
        String customerName = txtCustomerName.getText().trim(); // Make sure your TextField is named this!
        String phone = txtCustomerPhone.getText().trim();       // Make sure your TextField is named this!

        if (customerName.isEmpty() || phone.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter customer details.");
            return;
        }

        if (currentCart.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cart is empty!");
            return;
        }

        // 2. Create Sale Object
        // (Ensure your Sale model has a constructor that accepts name, phone, and ArrayList<Car>)
        model.Sale sale = new model.Sale(customerName, phone, currentCart);

        // 3. Add to Queue (FIFO Logic from Slide 44)
        controller.addSaleToQueue(sale);

        // 4. Success Message & Cleanup
        javax.swing.JOptionPane.showMessageDialog(this, "Order Queued Successfully!");

        currentCart.clear();      // Empty the local cart
        refreshCartTable();       // Clear the cart table UI
        txtCustomerName.setText("");
        txtCustomerPhone.setText("");

        // 5. Update the Admin View
        refreshPendingTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // 1. Open the Dialog
        // Pass 'this' as parent, 'true' for modal, and pass the controller & cart
        view.AddToCart dialog = new view.AddToCart(this, true, controller, currentCart);

        // 2. Center and Show
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        // 3. Update the Cart Table if something was added
        if (dialog.isItemAdded()) {
            refreshCartTable();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        // 1. Call the method you created in CarController
        // This handles the Dequeue -> Stock Update -> Stack Push logic
        model.Sale confirmedSale = controller.confirmNextSale();

        // 2. Check if it was successful
        if (confirmedSale != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Payment Confirmed for " + confirmedSale.getCustomerName());

            // 3. Update the GUI Tables
            refreshPendingTable(); // Updates the Queue table (Right Top)
            refreshHistoryTable(); // Updates the History table (Right Bottom)

            // 4. CRITICAL: Reload the Main Inventory Table to see the stock go down!
            loadTableData();

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No pending orders to confirm.");
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        model.Sale undoneSale = controller.undoLastSale();

        if (undoneSale != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Undo Successful. Stock restored for " + undoneSale.getCustomerName());

            // 2. Refresh Admin Tables
            refreshHistoryTable(); // Remove from History table

            // 3. CRITICAL: Refresh Main Inventory to see stock go UP
            loadTableData();

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Nothing to undo!");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        // 1. Check if there is anything to cancel
        if (controller.getPendingQueue().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No pending orders to cancel.");
            return;
        }

        // 2. Peek at who we are cancelling (User Experience improvement)
        // We use peek() so we can show the name BEFORE we delete it
        model.Sale nextSale = controller.getPendingQueue().peek();
        String customerName = (nextSale != null) ? nextSale.getCustomerName() : "Unknown";

        // 3. Ask for Confirmation
        int response = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to REJECT and CANCEL the order for " + customerName + "?\nThis action cannot be undone.",
                "Confirm Cancellation",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        // 4. Perform the Cancellation (Dequeue)
        if (response == javax.swing.JOptionPane.YES_OPTION) {
            model.Sale cancelled = controller.cancelNextSale();

            if (cancelled != null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Order Cancelled Successfully.");
                refreshPendingTable(); // Updates the UI to show the item is gone
            }
        }

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        // 1. Get User Selection
        String selection = (String) cmbSort.getSelectedItem(); // e.g., "Price (Low to High)"

        if (selection == null) {
            return;
        }

        // 2. Determine Ascending vs Descending
        // If selection is "Low to High", isAscending = true.
        // If selection is "High to Low", isAscending = false.
        boolean isAscending = selection.toLowerCase().contains("low to high");

        // 3. Call Bubble Sort
        controller.bubbleSort("price", isAscending);

        // 4. Refresh Table
        loadTableData();

        javax.swing.JOptionPane.showMessageDialog(this, "Sorted " + selection);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        // 1. Get Search Text
        String query = jTextField1.getText().trim(); // Check your TextField variable name

        // 2. Handle Empty Query
        if (query.isEmpty()) {
            // Restore default view (e.g., sort by Price Low to High)
            controller.bubbleSort("price", true);
            loadTableData();
            return;
        }

        // 3. Perform Smart Binary Search
        // This sorts by Brand -> Searches -> Sorts by Model -> Searches -> Merges
        java.util.ArrayList<model.Car> results = controller.searchByBrandAndModel(query);

        // 4. Update Table with Results
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) readTable.getModel();
        model.setRowCount(0); // Clear table

        for (model.Car car : results) {
            Object[] row = {
                car.getCarId(),
                car.getBrand(),
                car.getModel(),
                car.getYear(),
                car.getPrice(),
                car.getStockQuantity()
            };
            model.addRow(row);
        }

        // 5. Feedback
        if (results.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No matches found for: " + query);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbSort;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable readTable;
    private javax.swing.JTable tblCart;
    private javax.swing.JTable tblHistory;
    private javax.swing.JTable tblPending;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerPhone;
    private javax.swing.JTextField txtDeleteId;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtModel1;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtPrice1;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtQuantity1;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
